"use client";

import {
  Activity,
  BadgeIndianRupee,
  Building2,
  ClipboardCheck,
  FileWarning,
  Users,
} from "lucide-react";
import { useMemo } from "react";

import { BarChartCard, FunnelCard, KpiCard, PieChartCard, TrendCard } from "@/components/charts";
import { PageHeader } from "@/components/module";
import { Card, CardContent, StatusBadge } from "@/components/ui/primitives";
import { useMockStore } from "@/lib/store";
import { compactNumber, formatCurrency, formatDate } from "@/lib/utils";

function countBy<T>(items: T[], getKey: (item: T) => string) {
  return items.reduce<Record<string, number>>((acc, item) => {
    const key = getKey(item);
    acc[key] = (acc[key] ?? 0) + 1;
    return acc;
  }, {});
}

export function DashboardPage() {
  const { store } = useMockStore();

  const stats = useMemo(() => {
    const activeDsas = store.dsas.filter((item) => item.status === "Active").length;
    const approved = store.applications.filter((item) => item.status === "Approved" || item.status === "Disbursed");
    const totalPayout = store.commissions.reduce((sum, item) => sum + item.payout, 0);
    const riskQueue = store.applications.filter((item) => item.riskScore > 78 || item.status === "On Hold").length;
    return { activeDsas, approved: approved.length, riskQueue, totalPayout };
  }, [store]);

  const monthlyOnboarding = [
    { name: "Jan", value: 7 },
    { name: "Feb", value: 11 },
    { name: "Mar", value: 8 },
    { name: "Apr", value: 14 },
    { name: "May", value: 10 },
    { name: "Jun", value: 6 },
  ];

  const applicationTrend = [
    { name: "Jan", value: 36 },
    { name: "Feb", value: 44 },
    { name: "Mar", value: 52 },
    { name: "Apr", value: 49 },
    { name: "May", value: 61 },
    { name: "Jun", value: 58 },
  ];

  const sourceData = Object.entries(countBy(store.leads, (lead) => lead.source)).map(([name, value]) => ({
    name,
    value,
  }));

  const funnel = [
    { name: "Leads", value: store.leads.length },
    { name: "Qualified", value: store.leads.filter((item) => item.status === "Qualified").length + 42 },
    { name: "Applications", value: store.applications.length },
    { name: "Approved", value: stats.approved },
    { name: "Disbursed", value: store.applications.filter((item) => item.status === "Disbursed").length },
  ];

  return (
    <div>
      <PageHeader
        description="Command center for partner onboarding, lead velocity, underwriting health, verification queues, and payout exposure."
        eyebrow="Portfolio cockpit"
        title="Dashboard"
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <KpiCard change="+12.4%" icon={Building2} label="Active DSAs" tone="blue" value={String(stats.activeDsas)} />
        <KpiCard change="+9.1%" icon={ClipboardCheck} label="Approved applications" tone="green" value={String(stats.approved)} />
        <KpiCard change="-3.6%" icon={FileWarning} label="Risk queue" tone="amber" value={String(stats.riskQueue)} />
        <KpiCard change="+18.2%" icon={BadgeIndianRupee} label="Payout exposure" tone="slate" value={compactNumber(stats.totalPayout)} />
      </div>

      <div className="mt-6 grid gap-4 xl:grid-cols-2">
        <TrendCard
          data={monthlyOnboarding}
          dataKey="value"
          subtitle="New partner onboarding over the current fiscal window"
          title="Monthly onboarding trend"
          type="area"
        />
        <TrendCard
          data={applicationTrend}
          dataKey="value"
          subtitle="Application volume across DSA-sourced products"
          title="Application trend"
        />
      </div>

      <div className="mt-6 grid gap-4 xl:grid-cols-3">
        <FunnelCard data={funnel} subtitle="Lead-to-disbursal quality gate conversion" title="Approval funnel" />
        <PieChartCard data={sourceData} dataKey="value" subtitle="Lead contribution by acquisition channel" title="Lead source mix" />
        <BarChartCard
          data={store.commissions.slice(0, 6).map((item) => ({
            name: item.month.split(" ")[0],
            value: Math.round(item.payout / 1000),
          }))}
          dataKey="value"
          subtitle="Payouts in thousands across recent monthly batches"
          title="Commission run-rate"
        />
      </div>

      <div className="mt-6 grid gap-4 xl:grid-cols-[1.2fr_0.8fr]">
        <Card>
          <CardContent>
            <div className="mb-4 flex items-center justify-between">
              <div>
                <h2 className="text-base font-semibold text-slate-950">Recent activity</h2>
                <p className="text-sm text-slate-500">Audit events generated by workflows and users</p>
              </div>
              <Activity className="h-5 w-5 text-blue-600" />
            </div>
            <div className="space-y-3">
              {store.auditLogs.slice(0, 8).map((log) => (
                <div className="flex items-start gap-3 rounded-md border border-slate-100 p-3" key={log.id}>
                  <span className="mt-1 h-2 w-2 rounded-full bg-blue-600" />
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium text-slate-950">{log.action}</p>
                    <p className="text-xs text-slate-500">
                      {log.actor} · {log.entity} · {formatDate(log.at)}
                    </p>
                  </div>
                  <StatusBadge status={log.severity} />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent>
            <div className="mb-4 flex items-center justify-between">
              <div>
                <h2 className="text-base font-semibold text-slate-950">Operational queues</h2>
                <p className="text-sm text-slate-500">Work waiting for ownership today</p>
              </div>
              <Users className="h-5 w-5 text-blue-600" />
            </div>
            <div className="space-y-3">
              {[
                ["KYC pending DSAs", store.dsas.filter((item) => item.status === "KYC Pending").length],
                ["Verification checks", store.verificationChecks.filter((item) => item.status !== "Verified").length],
                ["Pending approvals", store.approvals.filter((item) => item.status === "Pending").length],
                ["Unread notifications", store.notifications.filter((item) => item.status === "Unread").length],
              ].map(([label, value]) => (
                <div className="flex items-center justify-between rounded-md bg-slate-50 p-3" key={label}>
                  <span className="text-sm text-slate-600">{label}</span>
                  <span className="text-lg font-semibold text-slate-950">{value}</span>
                </div>
              ))}
            </div>
            <div className="mt-4 rounded-md bg-blue-50 p-4">
              <p className="text-sm font-semibold text-blue-950">Projected commission liability</p>
              <p className="mt-1 text-2xl font-semibold text-blue-700">{formatCurrency(stats.totalPayout)}</p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
